Fix Travis CI Clang failure: Missing newline at end of file.
[ 14%] Building CXX object CMakeFiles/pngwriter_static.dir/src/pngwriter.cc.o
/home/travis/build/pkohut/pngwriter/src/pngwriter.cc:4625:2: error: no newline
      at end of file [-Werror,-Wnewline-eof]